# Generated by Django 4.2.7 on 2023-11-04 16:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="slug",
            field=autoslug.fields.AutoSlugField(default="test", unique=True),
            preserve_default=False,
        ),
    ]
