# Generated by Django 4.2.7 on 2023-11-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_newsletter_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="json_emails",
            field=models.JSONField(default=list, verbose_name="Emails list"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="emails",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Email par ligne.",
                verbose_name="Liste des e-mails",
            ),
        ),
    ]
