# Generated by Django 4.2.7 on 2023-11-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_newsletter_json_emails_alter_newsletter_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="emails",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Une adresse email par ligne.",
                verbose_name="Liste des e-mails",
            ),
        ),
    ]
