# Generated by Django 4.2.7 on 2023-11-06 10:54

from django.db import migrations, models
import easy_thumbnails.fields
import website.utils


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_newsletter_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=256, verbose_name="Nom de l'auteur"),
                ),
                (
                    "author_job",
                    models.CharField(
                        max_length=256, verbose_name="Fonction de l'auteur"
                    ),
                ),
                (
                    "author_picture",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        upload_to=website.utils.get_model_file_filename,
                        verbose_name="Image de l'auteur",
                    ),
                ),
                ("testimony", models.TextField(verbose_name="Témoignage")),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
            },
        ),
    ]
