# Generated by Django 4.2.7 on 2023-11-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="alignment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("topleft", "Top Left"),
                    ("top", "Top"),
                    ("topright", "Top Right"),
                    ("left", "Left"),
                    ("center", "Center"),
                    ("right", "Right"),
                    ("bottomleft", "Bottom Left"),
                    ("bottom", "Bottom"),
                    ("bottomright", "Bottom Right"),
                ],
                default="center",
                max_length=255,
                null=True,
                verbose_name="Alignment",
            ),
        ),
    ]
