# Generated by Django 4.2 on 2023-11-01 12:32

import autoslug.fields
import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/authors/avatars",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Profession"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Facebook"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Instagram"
                    ),
                ),
                (
                    "dribbble",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Dribble"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Twitter"
                    ),
                ),
                (
                    "youtube",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Youtube"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="Short description"),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Content"
                    ),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/posts_images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 11, 1, 13, 32, 58, 645541),
                        null=True,
                        verbose_name="Published at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blog.author",
                        verbose_name="Author",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="blog.category", verbose_name="Categories"
                    ),
                ),
                ("tags", models.ManyToManyField(to="blog.tag")),
            ],
            options={
                "ordering": ("-published_at", "-created_at"),
                "permissions": (("can_publish_post", "Can publish post"),),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rate this post from 1 to 5",
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(auto_now=True, verbose_name="Published_at"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replies",
                        to="blog.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
    ]
