# Generated by Django 4.2 on 2023-11-02 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="published_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Publication date"),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 11, 2, 16, 54, 25, 154337),
                null=True,
                verbose_name="Published at",
            ),
        ),
    ]
