# Generated by Django 4.2 on 2023-11-02 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_comment_published_at_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 11, 2, 16, 55, 0, 46351),
                null=True,
                verbose_name="Published at",
            ),
        ),
    ]
