# Generated by Django 4.2 on 2023-11-02 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 11, 2, 20, 4, 17, 178796),
                null=True,
                verbose_name="Published at",
            ),
        ),
    ]
