# Generated by Django 4.2.7 on 2023-11-06 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 11, 6, 11, 54, 55, 778128),
                null=True,
                verbose_name="Published at",
            ),
        ),
    ]
