# Generated by Django 4.2.7 on 2023-12-17 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 12, 17, 14, 11, 55, 765716),
                null=True,
                verbose_name="Published at",
            ),
        ),
    ]
