# Generated by Django 4.2.7 on 2024-01-16 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 1, 16, 12, 13, 58, 142625),
                null=True,
                verbose_name="Published at",
            ),
        ),
    ]
