# Generated by Django 4.2 on 2023-10-29 23:12

import club.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Montant"
                    ),
                ),
                ("reason", models.CharField(max_length=256, verbose_name="Motif")),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Nom du club")),
                (
                    "logo",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to=club.utils.get_club_logo_filename,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "sold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Solde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Club",
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Nom de la famille"),
                ),
            ],
            options={
                "verbose_name": "Famille",
                "verbose_name_plural": "Familles",
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to=club.utils.get_person_photo_filename,
                        verbose_name="Photo",
                    ),
                ),
                ("first_name", models.CharField(max_length=256, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=256, verbose_name="Nom")),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Lieu de naissance",
                    ),
                ),
                (
                    "cnie",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="CNIE"
                    ),
                ),
                (
                    "chronic_disease",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Souffrez-vous d’une maladie ?",
                    ),
                ),
                (
                    "disease_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Si oui, quelle est la maladie ?",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("city", "city"),
                            ("Casablanca", "Casablanca"),
                            ("El Kelaa des Srarhna", "El Kelaa des Srarhna"),
                            ("Fès", "Fès"),
                            ("Tangier", "Tangier"),
                            ("Marrakech", "Marrakech"),
                            ("Sale", "Sale"),
                            ("Mediouna", "Mediouna"),
                            ("Rabat", "Rabat"),
                            ("Meknès", "Meknès"),
                            ("Oujda-Angad", "Oujda-Angad"),
                            ("Kenitra", "Kenitra"),
                            ("Agadir", "Agadir"),
                            ("Tétouan", "Tétouan"),
                            ("Taourirt", "Taourirt"),
                            ("Temara", "Temara"),
                            ("Safi", "Safi"),
                            ("Khénifra", "Khénifra"),
                            ("Laâyoune", "Laâyoune"),
                            ("Mohammedia", "Mohammedia"),
                            ("Kouribga", "Kouribga"),
                            ("El Jadid", "El Jadid"),
                            ("Béni Mellal", "Béni Mellal"),
                            ("Ait Melloul", "Ait Melloul"),
                            ("Nador", "Nador"),
                            ("Taza", "Taza"),
                            ("Settat", "Settat"),
                            ("Barrechid", "Barrechid"),
                            ("Al Khmissat", "Al Khmissat"),
                            ("Inezgane", "Inezgane"),
                            ("Ksar El Kebir", "Ksar El Kebir"),
                            ("Larache", "Larache"),
                            ("Guelmim", "Guelmim"),
                            ("Berkane", "Berkane"),
                            ("Khemis Sahel", "Khemis Sahel"),
                            ("Ad Dakhla", "Ad Dakhla"),
                            ("Bouskoura", "Bouskoura"),
                            ("Al Fqih Ben Salah", "Al Fqih Ben Salah"),
                            ("Oued Zem", "Oued Zem"),
                            ("Sidi Slimane", "Sidi Slimane"),
                            ("Errachidia", "Errachidia"),
                            ("Guercif", "Guercif"),
                            ("Oulad Teïma", "Oulad Teïma"),
                            ("Ben Guerir", "Ben Guerir"),
                            ("Sefrou", "Sefrou"),
                            ("Fnidq", "Fnidq"),
                            ("Sidi Qacem", "Sidi Qacem"),
                            ("Moulay Abdallah", "Moulay Abdallah"),
                            ("Youssoufia", "Youssoufia"),
                            ("Martil", "Martil"),
                            ("Aïn Harrouda", "Aïn Harrouda"),
                            ("Skhirate", "Skhirate"),
                            ("Ouezzane", "Ouezzane"),
                            ("Sidi Yahya Zaer", "Sidi Yahya Zaer"),
                            ("Al Hoceïma", "Al Hoceïma"),
                            ("M’diq", "M’diq"),
                            ("Sidi Bennour", "Sidi Bennour"),
                            ("Midalt", "Midalt"),
                            ("Azrou", "Azrou"),
                            ("My Drarga", "My Drarga"),
                            ("Ain El Aouda", "Ain El Aouda"),
                            ("Beni Yakhlef", "Beni Yakhlef"),
                            ("Ad Darwa", "Ad Darwa"),
                            ("Al Aaroui", "Al Aaroui"),
                            ("Qasbat Tadla", "Qasbat Tadla"),
                            ("Boujad", "Boujad"),
                            ("Jerada", "Jerada"),
                            ("Mrirt", "Mrirt"),
                            ("El Aïoun", "El Aïoun"),
                            ("Azemmour", "Azemmour"),
                            ("Temsia", "Temsia"),
                            ("Zagora", "Zagora"),
                            ("Ait Ourir", "Ait Ourir"),
                            ("Aziylal", "Aziylal"),
                            ("Sidi Yahia El Gharb", "Sidi Yahia El Gharb"),
                            ("Biougra", "Biougra"),
                            ("Zaïo", "Zaïo"),
                            ("Aguelmous", "Aguelmous"),
                            ("El Hajeb", "El Hajeb"),
                            ("Zeghanghane", "Zeghanghane"),
                            ("Imzouren", "Imzouren"),
                            ("Tit Mellil", "Tit Mellil"),
                            ("Mechraa Bel Ksiri", "Mechraa Bel Ksiri"),
                            ("Al ’Attawia", "Al ’Attawia"),
                            ("Demnat", "Demnat"),
                            ("Arfoud", "Arfoud"),
                            ("Tameslouht", "Tameslouht"),
                            ("Bou Arfa", "Bou Arfa"),
                            ("Sidi Smai’il", "Sidi Smai’il"),
                            (
                                "Souk et Tnine Jorf el Mellah",
                                "Souk et Tnine Jorf el Mellah",
                            ),
                            ("Mehdya", "Mehdya"),
                            ("Aïn Taoujdat", "Aïn Taoujdat"),
                            ("Chichaoua", "Chichaoua"),
                            ("Tahla", "Tahla"),
                            ("Oulad Yaïch", "Oulad Yaïch"),
                            ("Moulay Bousselham", "Moulay Bousselham"),
                            ("Iheddadene", "Iheddadene"),
                            ("Missour", "Missour"),
                            ("Zawyat ech Cheïkh", "Zawyat ech Cheïkh"),
                            ("Bouknadel", "Bouknadel"),
                            ("Oulad Tayeb", "Oulad Tayeb"),
                            ("Oulad Barhil", "Oulad Barhil"),
                            ("Bir Jdid", "Bir Jdid"),
                            ("Tifariti", "Tifariti"),
                            ("other", "Autre"),
                        ],
                        default="Ait Ourir",
                        max_length=256,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Code postal"
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Adresse"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "fix_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Numéro de téléphone fixe",
                    ),
                ),
                (
                    "facebook_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte Facebook",
                    ),
                ),
                (
                    "instagram_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte Instagram",
                    ),
                ),
                (
                    "tiktok_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte TikTok",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tuteur",
                "verbose_name_plural": "Tuteurs",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Nom d'abonnement"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "recurring_payment",
                    models.BooleanField(
                        default=True,
                        help_text="Un seule paiement a vie, ou bien un paiement chaque period (mois ou année).",
                        verbose_name="Paiement récurrent",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("month", "Mois"), ("year", "Année")],
                        max_length=16,
                        verbose_name="Period",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Montant"
                    ),
                ),
                (
                    "has_insurance",
                    models.BooleanField(
                        default=True, verbose_name="Contient une assurance"
                    ),
                ),
                (
                    "insurance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Le montant à payer pour l'assurance.",
                        max_digits=8,
                        verbose_name="Montant d'assurance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to=club.utils.get_person_photo_filename,
                        verbose_name="Photo",
                    ),
                ),
                ("first_name", models.CharField(max_length=256, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=256, verbose_name="Nom")),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Lieu de naissance",
                    ),
                ),
                (
                    "cnie",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="CNIE"
                    ),
                ),
                (
                    "chronic_disease",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Souffrez-vous d’une maladie ?",
                    ),
                ),
                (
                    "disease_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Si oui, quelle est la maladie ?",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("city", "city"),
                            ("Casablanca", "Casablanca"),
                            ("El Kelaa des Srarhna", "El Kelaa des Srarhna"),
                            ("Fès", "Fès"),
                            ("Tangier", "Tangier"),
                            ("Marrakech", "Marrakech"),
                            ("Sale", "Sale"),
                            ("Mediouna", "Mediouna"),
                            ("Rabat", "Rabat"),
                            ("Meknès", "Meknès"),
                            ("Oujda-Angad", "Oujda-Angad"),
                            ("Kenitra", "Kenitra"),
                            ("Agadir", "Agadir"),
                            ("Tétouan", "Tétouan"),
                            ("Taourirt", "Taourirt"),
                            ("Temara", "Temara"),
                            ("Safi", "Safi"),
                            ("Khénifra", "Khénifra"),
                            ("Laâyoune", "Laâyoune"),
                            ("Mohammedia", "Mohammedia"),
                            ("Kouribga", "Kouribga"),
                            ("El Jadid", "El Jadid"),
                            ("Béni Mellal", "Béni Mellal"),
                            ("Ait Melloul", "Ait Melloul"),
                            ("Nador", "Nador"),
                            ("Taza", "Taza"),
                            ("Settat", "Settat"),
                            ("Barrechid", "Barrechid"),
                            ("Al Khmissat", "Al Khmissat"),
                            ("Inezgane", "Inezgane"),
                            ("Ksar El Kebir", "Ksar El Kebir"),
                            ("Larache", "Larache"),
                            ("Guelmim", "Guelmim"),
                            ("Berkane", "Berkane"),
                            ("Khemis Sahel", "Khemis Sahel"),
                            ("Ad Dakhla", "Ad Dakhla"),
                            ("Bouskoura", "Bouskoura"),
                            ("Al Fqih Ben Salah", "Al Fqih Ben Salah"),
                            ("Oued Zem", "Oued Zem"),
                            ("Sidi Slimane", "Sidi Slimane"),
                            ("Errachidia", "Errachidia"),
                            ("Guercif", "Guercif"),
                            ("Oulad Teïma", "Oulad Teïma"),
                            ("Ben Guerir", "Ben Guerir"),
                            ("Sefrou", "Sefrou"),
                            ("Fnidq", "Fnidq"),
                            ("Sidi Qacem", "Sidi Qacem"),
                            ("Moulay Abdallah", "Moulay Abdallah"),
                            ("Youssoufia", "Youssoufia"),
                            ("Martil", "Martil"),
                            ("Aïn Harrouda", "Aïn Harrouda"),
                            ("Skhirate", "Skhirate"),
                            ("Ouezzane", "Ouezzane"),
                            ("Sidi Yahya Zaer", "Sidi Yahya Zaer"),
                            ("Al Hoceïma", "Al Hoceïma"),
                            ("M’diq", "M’diq"),
                            ("Sidi Bennour", "Sidi Bennour"),
                            ("Midalt", "Midalt"),
                            ("Azrou", "Azrou"),
                            ("My Drarga", "My Drarga"),
                            ("Ain El Aouda", "Ain El Aouda"),
                            ("Beni Yakhlef", "Beni Yakhlef"),
                            ("Ad Darwa", "Ad Darwa"),
                            ("Al Aaroui", "Al Aaroui"),
                            ("Qasbat Tadla", "Qasbat Tadla"),
                            ("Boujad", "Boujad"),
                            ("Jerada", "Jerada"),
                            ("Mrirt", "Mrirt"),
                            ("El Aïoun", "El Aïoun"),
                            ("Azemmour", "Azemmour"),
                            ("Temsia", "Temsia"),
                            ("Zagora", "Zagora"),
                            ("Ait Ourir", "Ait Ourir"),
                            ("Aziylal", "Aziylal"),
                            ("Sidi Yahia El Gharb", "Sidi Yahia El Gharb"),
                            ("Biougra", "Biougra"),
                            ("Zaïo", "Zaïo"),
                            ("Aguelmous", "Aguelmous"),
                            ("El Hajeb", "El Hajeb"),
                            ("Zeghanghane", "Zeghanghane"),
                            ("Imzouren", "Imzouren"),
                            ("Tit Mellil", "Tit Mellil"),
                            ("Mechraa Bel Ksiri", "Mechraa Bel Ksiri"),
                            ("Al ’Attawia", "Al ’Attawia"),
                            ("Demnat", "Demnat"),
                            ("Arfoud", "Arfoud"),
                            ("Tameslouht", "Tameslouht"),
                            ("Bou Arfa", "Bou Arfa"),
                            ("Sidi Smai’il", "Sidi Smai’il"),
                            (
                                "Souk et Tnine Jorf el Mellah",
                                "Souk et Tnine Jorf el Mellah",
                            ),
                            ("Mehdya", "Mehdya"),
                            ("Aïn Taoujdat", "Aïn Taoujdat"),
                            ("Chichaoua", "Chichaoua"),
                            ("Tahla", "Tahla"),
                            ("Oulad Yaïch", "Oulad Yaïch"),
                            ("Moulay Bousselham", "Moulay Bousselham"),
                            ("Iheddadene", "Iheddadene"),
                            ("Missour", "Missour"),
                            ("Zawyat ech Cheïkh", "Zawyat ech Cheïkh"),
                            ("Bouknadel", "Bouknadel"),
                            ("Oulad Tayeb", "Oulad Tayeb"),
                            ("Oulad Barhil", "Oulad Barhil"),
                            ("Bir Jdid", "Bir Jdid"),
                            ("Tifariti", "Tifariti"),
                            ("other", "Autre"),
                        ],
                        default="Ait Ourir",
                        max_length=256,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Code postal"
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Adresse"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "fix_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Numéro de téléphone fixe",
                    ),
                ),
                (
                    "facebook_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte Facebook",
                    ),
                ),
                (
                    "instagram_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte Instagram",
                    ),
                ),
                (
                    "tiktok_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte TikTok",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="club.family",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="club.guardian",
                        verbose_name="Tuteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonné(e)",
                "verbose_name_plural": "Abonné(e)s",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d’adhésion"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="club.plan",
                        verbose_name="Abonnement",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="club.subscriber",
                        verbose_name="Adhérant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adhésion",
                "verbose_name_plural": "Adhésions",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Montant"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="club.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to=club.utils.get_person_photo_filename,
                        verbose_name="Photo",
                    ),
                ),
                ("first_name", models.CharField(max_length=256, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=256, verbose_name="Nom")),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Lieu de naissance",
                    ),
                ),
                (
                    "cnie",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="CNIE"
                    ),
                ),
                (
                    "chronic_disease",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Souffrez-vous d’une maladie ?",
                    ),
                ),
                (
                    "disease_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Si oui, quelle est la maladie ?",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("city", "city"),
                            ("Casablanca", "Casablanca"),
                            ("El Kelaa des Srarhna", "El Kelaa des Srarhna"),
                            ("Fès", "Fès"),
                            ("Tangier", "Tangier"),
                            ("Marrakech", "Marrakech"),
                            ("Sale", "Sale"),
                            ("Mediouna", "Mediouna"),
                            ("Rabat", "Rabat"),
                            ("Meknès", "Meknès"),
                            ("Oujda-Angad", "Oujda-Angad"),
                            ("Kenitra", "Kenitra"),
                            ("Agadir", "Agadir"),
                            ("Tétouan", "Tétouan"),
                            ("Taourirt", "Taourirt"),
                            ("Temara", "Temara"),
                            ("Safi", "Safi"),
                            ("Khénifra", "Khénifra"),
                            ("Laâyoune", "Laâyoune"),
                            ("Mohammedia", "Mohammedia"),
                            ("Kouribga", "Kouribga"),
                            ("El Jadid", "El Jadid"),
                            ("Béni Mellal", "Béni Mellal"),
                            ("Ait Melloul", "Ait Melloul"),
                            ("Nador", "Nador"),
                            ("Taza", "Taza"),
                            ("Settat", "Settat"),
                            ("Barrechid", "Barrechid"),
                            ("Al Khmissat", "Al Khmissat"),
                            ("Inezgane", "Inezgane"),
                            ("Ksar El Kebir", "Ksar El Kebir"),
                            ("Larache", "Larache"),
                            ("Guelmim", "Guelmim"),
                            ("Berkane", "Berkane"),
                            ("Khemis Sahel", "Khemis Sahel"),
                            ("Ad Dakhla", "Ad Dakhla"),
                            ("Bouskoura", "Bouskoura"),
                            ("Al Fqih Ben Salah", "Al Fqih Ben Salah"),
                            ("Oued Zem", "Oued Zem"),
                            ("Sidi Slimane", "Sidi Slimane"),
                            ("Errachidia", "Errachidia"),
                            ("Guercif", "Guercif"),
                            ("Oulad Teïma", "Oulad Teïma"),
                            ("Ben Guerir", "Ben Guerir"),
                            ("Sefrou", "Sefrou"),
                            ("Fnidq", "Fnidq"),
                            ("Sidi Qacem", "Sidi Qacem"),
                            ("Moulay Abdallah", "Moulay Abdallah"),
                            ("Youssoufia", "Youssoufia"),
                            ("Martil", "Martil"),
                            ("Aïn Harrouda", "Aïn Harrouda"),
                            ("Skhirate", "Skhirate"),
                            ("Ouezzane", "Ouezzane"),
                            ("Sidi Yahya Zaer", "Sidi Yahya Zaer"),
                            ("Al Hoceïma", "Al Hoceïma"),
                            ("M’diq", "M’diq"),
                            ("Sidi Bennour", "Sidi Bennour"),
                            ("Midalt", "Midalt"),
                            ("Azrou", "Azrou"),
                            ("My Drarga", "My Drarga"),
                            ("Ain El Aouda", "Ain El Aouda"),
                            ("Beni Yakhlef", "Beni Yakhlef"),
                            ("Ad Darwa", "Ad Darwa"),
                            ("Al Aaroui", "Al Aaroui"),
                            ("Qasbat Tadla", "Qasbat Tadla"),
                            ("Boujad", "Boujad"),
                            ("Jerada", "Jerada"),
                            ("Mrirt", "Mrirt"),
                            ("El Aïoun", "El Aïoun"),
                            ("Azemmour", "Azemmour"),
                            ("Temsia", "Temsia"),
                            ("Zagora", "Zagora"),
                            ("Ait Ourir", "Ait Ourir"),
                            ("Aziylal", "Aziylal"),
                            ("Sidi Yahia El Gharb", "Sidi Yahia El Gharb"),
                            ("Biougra", "Biougra"),
                            ("Zaïo", "Zaïo"),
                            ("Aguelmous", "Aguelmous"),
                            ("El Hajeb", "El Hajeb"),
                            ("Zeghanghane", "Zeghanghane"),
                            ("Imzouren", "Imzouren"),
                            ("Tit Mellil", "Tit Mellil"),
                            ("Mechraa Bel Ksiri", "Mechraa Bel Ksiri"),
                            ("Al ’Attawia", "Al ’Attawia"),
                            ("Demnat", "Demnat"),
                            ("Arfoud", "Arfoud"),
                            ("Tameslouht", "Tameslouht"),
                            ("Bou Arfa", "Bou Arfa"),
                            ("Sidi Smai’il", "Sidi Smai’il"),
                            (
                                "Souk et Tnine Jorf el Mellah",
                                "Souk et Tnine Jorf el Mellah",
                            ),
                            ("Mehdya", "Mehdya"),
                            ("Aïn Taoujdat", "Aïn Taoujdat"),
                            ("Chichaoua", "Chichaoua"),
                            ("Tahla", "Tahla"),
                            ("Oulad Yaïch", "Oulad Yaïch"),
                            ("Moulay Bousselham", "Moulay Bousselham"),
                            ("Iheddadene", "Iheddadene"),
                            ("Missour", "Missour"),
                            ("Zawyat ech Cheïkh", "Zawyat ech Cheïkh"),
                            ("Bouknadel", "Bouknadel"),
                            ("Oulad Tayeb", "Oulad Tayeb"),
                            ("Oulad Barhil", "Oulad Barhil"),
                            ("Bir Jdid", "Bir Jdid"),
                            ("Tifariti", "Tifariti"),
                            ("other", "Autre"),
                        ],
                        default="Ait Ourir",
                        max_length=256,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Code postal"
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Adresse"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "fix_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Numéro de téléphone fixe",
                    ),
                ),
                (
                    "facebook_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte Facebook",
                    ),
                ),
                (
                    "instagram_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte Instagram",
                    ),
                ),
                (
                    "tiktok_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte TikTok",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
            },
        ),
    ]
