# Generated by Django 4.2 on 2023-10-29 23:57

import club.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        default=club.utils.current_year, verbose_name="Année"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Le montant à payer pour l'assurance.",
                        max_digits=8,
                        verbose_name="Montant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assurance",
                "verbose_name_plural": "Assurances",
            },
        ),
        migrations.AlterModelOptions(
            name="charge",
            options={"verbose_name": "Dépense", "verbose_name_plural": "Dépenses"},
        ),
        migrations.RemoveField(
            model_name="plan",
            name="has_insurance",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="insurance_amount",
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur associé",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="club.family",
                verbose_name="Famille",
            ),
        ),
    ]
