# Generated by Django 4.2 on 2023-10-30 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club", "0002_insurance_alter_charge_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Membre"),
                    ("executive_director", "Directeur exécutif"),
                    ("board_of_directors", "Conseil d'administration"),
                    ("program_manager", "Gestionnaire de programme"),
                    (
                        "fundraising_coordinator",
                        "Coordinateur / Coordinatrice de collecte de fonds",
                    ),
                    (
                        "volunteer_coordinator",
                        "Coordinateur / Coordinatrice de bénévoles",
                    ),
                    (
                        "finance_manager",
                        "Responsable financier / Responsable financière",
                    ),
                    (
                        "marketing_communications_manager",
                        "Responsable marketing et communication",
                    ),
                    ("grant_writer", "Rédacteur / Rédactrice de subventions"),
                    (
                        "administrative_assistant",
                        "Assistant administratif / Assistante administrative",
                    ),
                    (
                        "advocacy_policy_specialist",
                        "Spécialiste de la sensibilisation et de la politique",
                    ),
                ],
                default="member",
                max_length=64,
                verbose_name="Fonction",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="insurance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="club.insurance",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur associé",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="club.subscription",
            ),
        ),
    ]
