# Generated by Django 4.2 on 2023-11-02 15:54

import club.utils
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0004_payment_subscriber_alter_payment_insurance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to=club.utils.get_person_photo_filename,
                        verbose_name="Photo",
                    ),
                ),
                ("first_name", models.CharField(max_length=256, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=256, verbose_name="Nom")),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Lieu de naissance",
                    ),
                ),
                (
                    "cnie",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="CNIE"
                    ),
                ),
                (
                    "chronic_disease",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Souffrez-vous d’une maladie ?",
                    ),
                ),
                (
                    "disease_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Si oui, quelle est la maladie ?",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("city", "city"),
                            ("Casablanca", "Casablanca"),
                            ("El Kelaa des Srarhna", "El Kelaa des Srarhna"),
                            ("Fès", "Fès"),
                            ("Tangier", "Tangier"),
                            ("Marrakech", "Marrakech"),
                            ("Sale", "Sale"),
                            ("Mediouna", "Mediouna"),
                            ("Rabat", "Rabat"),
                            ("Meknès", "Meknès"),
                            ("Oujda-Angad", "Oujda-Angad"),
                            ("Kenitra", "Kenitra"),
                            ("Agadir", "Agadir"),
                            ("Tétouan", "Tétouan"),
                            ("Taourirt", "Taourirt"),
                            ("Temara", "Temara"),
                            ("Safi", "Safi"),
                            ("Khénifra", "Khénifra"),
                            ("Laâyoune", "Laâyoune"),
                            ("Mohammedia", "Mohammedia"),
                            ("Kouribga", "Kouribga"),
                            ("El Jadid", "El Jadid"),
                            ("Béni Mellal", "Béni Mellal"),
                            ("Ait Melloul", "Ait Melloul"),
                            ("Nador", "Nador"),
                            ("Taza", "Taza"),
                            ("Settat", "Settat"),
                            ("Barrechid", "Barrechid"),
                            ("Al Khmissat", "Al Khmissat"),
                            ("Inezgane", "Inezgane"),
                            ("Ksar El Kebir", "Ksar El Kebir"),
                            ("Larache", "Larache"),
                            ("Guelmim", "Guelmim"),
                            ("Berkane", "Berkane"),
                            ("Khemis Sahel", "Khemis Sahel"),
                            ("Ad Dakhla", "Ad Dakhla"),
                            ("Bouskoura", "Bouskoura"),
                            ("Al Fqih Ben Salah", "Al Fqih Ben Salah"),
                            ("Oued Zem", "Oued Zem"),
                            ("Sidi Slimane", "Sidi Slimane"),
                            ("Errachidia", "Errachidia"),
                            ("Guercif", "Guercif"),
                            ("Oulad Teïma", "Oulad Teïma"),
                            ("Ben Guerir", "Ben Guerir"),
                            ("Sefrou", "Sefrou"),
                            ("Fnidq", "Fnidq"),
                            ("Sidi Qacem", "Sidi Qacem"),
                            ("Moulay Abdallah", "Moulay Abdallah"),
                            ("Youssoufia", "Youssoufia"),
                            ("Martil", "Martil"),
                            ("Aïn Harrouda", "Aïn Harrouda"),
                            ("Skhirate", "Skhirate"),
                            ("Ouezzane", "Ouezzane"),
                            ("Sidi Yahya Zaer", "Sidi Yahya Zaer"),
                            ("Al Hoceïma", "Al Hoceïma"),
                            ("M’diq", "M’diq"),
                            ("Sidi Bennour", "Sidi Bennour"),
                            ("Midalt", "Midalt"),
                            ("Azrou", "Azrou"),
                            ("My Drarga", "My Drarga"),
                            ("Ain El Aouda", "Ain El Aouda"),
                            ("Beni Yakhlef", "Beni Yakhlef"),
                            ("Ad Darwa", "Ad Darwa"),
                            ("Al Aaroui", "Al Aaroui"),
                            ("Qasbat Tadla", "Qasbat Tadla"),
                            ("Boujad", "Boujad"),
                            ("Jerada", "Jerada"),
                            ("Mrirt", "Mrirt"),
                            ("El Aïoun", "El Aïoun"),
                            ("Azemmour", "Azemmour"),
                            ("Temsia", "Temsia"),
                            ("Zagora", "Zagora"),
                            ("Ait Ourir", "Ait Ourir"),
                            ("Aziylal", "Aziylal"),
                            ("Sidi Yahia El Gharb", "Sidi Yahia El Gharb"),
                            ("Biougra", "Biougra"),
                            ("Zaïo", "Zaïo"),
                            ("Aguelmous", "Aguelmous"),
                            ("El Hajeb", "El Hajeb"),
                            ("Zeghanghane", "Zeghanghane"),
                            ("Imzouren", "Imzouren"),
                            ("Tit Mellil", "Tit Mellil"),
                            ("Mechraa Bel Ksiri", "Mechraa Bel Ksiri"),
                            ("Al ’Attawia", "Al ’Attawia"),
                            ("Demnat", "Demnat"),
                            ("Arfoud", "Arfoud"),
                            ("Tameslouht", "Tameslouht"),
                            ("Bou Arfa", "Bou Arfa"),
                            ("Sidi Smai’il", "Sidi Smai’il"),
                            (
                                "Souk et Tnine Jorf el Mellah",
                                "Souk et Tnine Jorf el Mellah",
                            ),
                            ("Mehdya", "Mehdya"),
                            ("Aïn Taoujdat", "Aïn Taoujdat"),
                            ("Chichaoua", "Chichaoua"),
                            ("Tahla", "Tahla"),
                            ("Oulad Yaïch", "Oulad Yaïch"),
                            ("Moulay Bousselham", "Moulay Bousselham"),
                            ("Iheddadene", "Iheddadene"),
                            ("Missour", "Missour"),
                            ("Zawyat ech Cheïkh", "Zawyat ech Cheïkh"),
                            ("Bouknadel", "Bouknadel"),
                            ("Oulad Tayeb", "Oulad Tayeb"),
                            ("Oulad Barhil", "Oulad Barhil"),
                            ("Bir Jdid", "Bir Jdid"),
                            ("Tifariti", "Tifariti"),
                            ("other", "Autre"),
                        ],
                        default="Ait Ourir",
                        max_length=256,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Code postal"
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Adresse"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "fix_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Numéro de téléphone fixe",
                    ),
                ),
                (
                    "facebook_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte Facebook",
                    ),
                ),
                (
                    "instagram_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte Instagram",
                    ),
                ),
                (
                    "tiktok_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Compte TikTok",
                    ),
                ),
                (
                    "elo",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ELO"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="club.family",
                        verbose_name="Famille",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="club.guardian",
                        verbose_name="Tuteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Joueur",
                "verbose_name_plural": "Joueurs",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="subscriber",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="subscriber",
        ),
        migrations.AddField(
            model_name="payment",
            name="donator",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Donneur / Donneuse"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="type_payment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non spécifié"),
                    ("subscription_payment", "Paiement d'adhésion"),
                    ("insurance_payment", "Paiement d'assurance"),
                    ("donation", "Un don"),
                ],
                default="",
                max_length=32,
                verbose_name="Type de paiement",
            ),
        ),
        migrations.DeleteModel(
            name="Subscriber",
        ),
        migrations.AddField(
            model_name="payment",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="club.player",
                verbose_name="Adhérant",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="player",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="club.player",
                verbose_name="Adhérant",
            ),
            preserve_default=False,
        ),
    ]
