# Generated by Django 4.2 on 2023-11-02 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0005_player_remove_payment_subscriber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 11, 2, 16, 23, 32, 991000, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date de paiement",
            ),
            preserve_default=False,
        ),
    ]
