# Generated by Django 4.2 on 2023-11-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0007_charge_expense_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Charge",
            new_name="Expense",
        ),
    ]
