# Generated by Django 4.2 on 2023-11-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0008_rename_charge_expense"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"verbose_name": "Personne", "verbose_name_plural": "Personnes`"},
        ),
        migrations.AddField(
            model_name="payment",
            name="reason",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="Motif"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type_payment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non spécifié"),
                    ("subscription_payment", "Paiement d'adhésion"),
                    ("insurance_payment", "Paiement d'assurance"),
                    ("donation", "Un don"),
                    ("other", "Autre"),
                ],
                default="",
                max_length=32,
                verbose_name="Type de paiement",
            ),
        ),
    ]
