# Generated by Django 4.2.7 on 2023-11-03 17:30

import club.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0010_payment_anonyme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Titre")),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'album"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=club.utils.get_model_file_filename,
                        verbose_name="Image",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Titre")),
                (
                    "book_file",
                    models.FileField(
                        upload_to=club.utils.get_book_file_filename,
                        verbose_name="Livre",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Catégorie"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Auteur"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de sortie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Livre",
                "verbose_name_plural": "Livres",
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=club.utils.get_model_file_filename,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Titre"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de capture"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="club.album",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Médiathèque",
            },
        ),
    ]
