# Generated by Django 4.2.7 on 2023-11-03 19:28

import autoslug.fields
from django.db import migrations, models
import random


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0011_album_book_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="title"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="album",
            name="title",
            field=models.CharField(max_length=256, unique=True, verbose_name="Titre"),
        ),
    ]
