# Generated by Django 4.2.7 on 2023-11-03 19:43

import autoslug.fields
import club.utils
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0012_album_slug_alter_album_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                upload_to=club.utils.get_model_file_filename, verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="photo",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                upload_to=club.utils.get_model_file_filename, verbose_name="Photo"
            ),
        ),
    ]
