# Generated by Django 4.2.7 on 2023-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0015_session"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ("-start_date", "-end_date"),
                "verbose_name": "Seance",
                "verbose_name_plural": "Seances",
            },
        ),
        migrations.AlterField(
            model_name="committeemember",
            name="role",
            field=models.CharField(
                choices=[
                    ("coordinator", "Coordinateur / Coordinatrice"),
                    ("deputy", "Adjoint"),
                ],
                default="member",
                max_length=64,
                verbose_name="Fonction",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("president", "Président"),
                    ("vice_president", "Vice président"),
                    ("secretary_general", "Secrétaire générale"),
                    ("vice_secretary_general", "Vice secrétaire générale"),
                    ("treasurer", "Trésorier"),
                    ("vice_treasurer", "Vice trésorier"),
                    ("council_member", "Conseiller"),
                ],
                default="member",
                max_length=64,
                verbose_name="Fonction",
            ),
        ),
    ]
