# Generated by Django 4.2.7 on 2024-01-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0018_alter_committee_name_alter_member_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"verbose_name": "Adhérant", "verbose_name_plural": "Adhérants"},
        ),
    ]
