from django.conf import settings
from django.utils.translation import gettext_lazy as _


PERIOD_CHOICES = (
    ("month", _("Mois")),
    ("year", _("Année")),
)


MEMBER_ROLE_CHOICES = getattr(settings, "MEMBER_ROLE_CHOICES", (
    ("member", _("Membre")),
    ("executive_director", _("Directeur exécutif")),
    ("board_of_directors", _("Conseil d'administration")),
    ("program_manager", _("Gestionnaire de programme")),
    ("fundraising_coordinator", _("Coordinateur / Coordinatrice de collecte de fonds")),
    ("volunteer_coordinator", _("Coordinateur / Coordinatrice de bénévoles")),
    ("finance_manager", _("Responsable financier / Responsable financière")),
    ("marketing_communications_manager", _("Responsable marketing et communication")),
    ("grant_writer", _("Rédacteur / Rédactrice de subventions")),
    ("administrative_assistant", _("Assistant administratif / Assistante administrative")),
    ("advocacy_policy_specialist", _("Spécialiste de la sensibilisation et de la politique")),
))


COMMITTEE_MEMBER_ROLE_CHOICES = getattr(settings, "COMMITTEE_MEMBER_ROLE_CHOICES", (
    ("director", _("Directeur de comité")),
    ("member", _("Membre de comité")),
    ("active_member", _("Membre actif de comité")),
))


COUNTRIES = (
    ("Yemen", "Yemen"),
    ("Vietnam", "Vietnam"),
    ("Venezuela", "Venezuela"),
    ("Vanuatu", "Vanuatu"),
    ("Uzbekistan", "Uzbekistan"),
    ("Uruguay", "Uruguay"),
    ("United States of America", "United States of America"),
    ("United Kingdom", "United Kingdom"),
    ("United Arab Emirates", "United Arab Emirates"),
    ("Ukraine", "Ukraine"),
    ("Uganda", "Uganda"),
    ("Tuvalu", "Tuvalu"),
    ("Turkmenistan", "Turkmenistan"),
    ("Turkey", "Turkey"),
    ("Tunisia", "Tunisia"),
    ("Trinidad and Tobago", "Trinidad and Tobago"),
    ("Tonga", "Tonga"),
    ("Togo", "Togo"),
    ("Timor-Leste", "Timor-Leste"),
    ("Thailand", "Thailand"),
    ("Tanzania", "Tanzania"),
    ("Tajikistan", "Tajikistan"),
    ("Syria", "Syria"),
    ("Switzerland", "Switzerland"),
    ("Sweden", "Sweden"),
    ("Suriname", "Suriname"),
    ("Sudan", "Sudan"),
    ("Sri Lanka", "Sri Lanka"),
    ("Spain", "Spain"),
    ("South Sudan", "South Sudan"),
    ("South Korea", "South Korea"),
    ("South Africa", "South Africa"),
    ("Somalia", "Somalia"),
    ("Solomon Islands", "Solomon Islands"),
    ("Slovenia", "Slovenia"),
    ("Slovakia", "Slovakia"),
    ("Singapore", "Singapore"),
    ("Sierra Leone", "Sierra Leone"),
    ("Seychelles", "Seychelles"),
    ("Serbia", "Serbia"),
    ("Senegal", "Senegal"),
    ("Saudi Arabia", "Saudi Arabia"),
    ("Sao Tome and Principe", "Sao Tome and Principe"),
    ("San Marino", "San Marino"),
    ("Samoa", "Samoa"),
    ("Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"),
    ("Saint Lucia", "Saint Lucia"),
    ("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
    ("Rwanda", "Rwanda"),
    ("Russia", "Russia"),
    ("Romania", "Romania"),
    ("Qatar", "Qatar"),
    ("Portugal", "Portugal"),
    ("Poland", "Poland"),
    ("Philippines", "Philippines"),
    ("Peru", "Peru"),
    ("Paraguay", "Paraguay"),
    ("Papua New Guinea", "Papua New Guinea"),
    ("Panama", "Panama"),
    ("Palestine State", "Palestine State"),
    ("Palau", "Palau"),
    ("Pakistan", "Pakistan"),
    ("Oman", "Oman"),
    ("Norway", "Norway"),
    ("North Macedonia", "North Macedonia"),
    ("North Korea", "North Korea"),
    ("Nigeria", "Nigeria"),
    ("Niger", "Niger"),
    ("Nicaragua", "Nicaragua"),
    ("New Zealand", "New Zealand"),
    ("Netherlands", "Netherlands"),
    ("Nepal", "Nepal"),
    ("Nauru", "Nauru"),
    ("Namibia", "Namibia"),
    ("Myanmar (formerly Burma)", "Myanmar (formerly Burma)"),
    ("Mozambique", "Mozambique"),
    ("Morocco", "Morocco"),
    ("Montenegro", "Montenegro"),
    ("Mongolia", "Mongolia"),
    ("Monaco", "Monaco"),
    ("Moldova", "Moldova"),
    ("Micronesia", "Micronesia"),
    ("Mexico", "Mexico"),
    ("Mauritius", "Mauritius"),
    ("Mauritania", "Mauritania"),
    ("Marshall Islands", "Marshall Islands"),
    ("Malta", "Malta"),
    ("Mali", "Mali"),
    ("Maldives", "Maldives"),
    ("Malaysia", "Malaysia"),
    ("Malawi", "Malawi"),
    ("Madagascar", "Madagascar"),
    ("Luxembourg", "Luxembourg"),
    ("Lithuania", "Lithuania"),
    ("Liechtenstein", "Liechtenstein"),
    ("Libya", "Libya"),
    ("Liberia", "Liberia"),
    ("Lesotho", "Lesotho"),
    ("Lebanon", "Lebanon"),
    ("Latvia", "Latvia"),
    ("Laos", "Laos"),
    ("Kyrgyzstan", "Kyrgyzstan"),
    ("Kuwait", "Kuwait"),
    ("Kiribati", "Kiribati"),
    ("Kenya", "Kenya"),
    ("Kazakhstan", "Kazakhstan"),
    ("Jordan", "Jordan"),
    ("Japan", "Japan"),
    ("Jamaica", "Jamaica"),
    ("Italy", "Italy"),
    ("Israel", "Israel"),
    ("Ireland", "Ireland"),
    ("Iraq", "Iraq"),
    ("Iran", "Iran"),
    ("Indonesia", "Indonesia"),
    ("India", "India"),
    ("Iceland", "Iceland"),
    ("Hungary", "Hungary"),
    ("Honduras", "Honduras"),
    ("Holy See	518	0", "Holy See	518	0"),
    ("Haiti", "Haiti"),
    ("Guyana", "Guyana"),
    ("Guinea-Bissau", "Guinea-Bissau"),
    ("Guinea", "Guinea"),
    ("Guatemala", "Guatemala"),
    ("Grenada", "Grenada"),
    ("Greece", "Greece"),
    ("Ghana", "Ghana"),
    ("Germany", "Germany"),
    ("Georgia", "Georgia"),
    ("Gambia", "Gambia"),
    ("Gabon", "Gabon"),
    ("France", "France"),
    ("Finland", "Finland"),
    ("Fiji", "Fiji"),
    ("Ethiopia", "Ethiopia"),
    ("Eswatini (fmr. 'Swaziland')", "Eswatini (fmr. 'Swaziland')"),
    ("Estonia", "Estonia"),
    ("Eritrea", "Eritrea"),
    ("Equatorial Guinea", "Equatorial Guinea"),
    ("El Salvador", "El Salvador"),
    ("Egypt", "Egypt"),
    ("Ecuador", "Ecuador"),
    ("Dominican Republic", "Dominican Republic"),
    ("Dominica", "Dominica"),
    ("Djibouti", "Djibouti"),
    ("Denmark", "Denmark"),
    ("Democratic Republic of the Congo", "Democratic Republic of the Congo"),
    ("Czechia (Czech Republic)", "Czechia (Czech Republic)"),
    ("Cyprus", "Cyprus"),
    ("Cuba", "Cuba"),
    ("Croatia", "Croatia"),
    ("Costa Rica", "Costa Rica"),
    ("Congo (Congo-Brazzaville)", "Congo (Congo-Brazzaville)"),
    ("Comoros", "Comoros"),
    ("Colombia", "Colombia"),
    ("China", "China"),
    ("Chile", "Chile"),
    ("Chad", "Chad"),
    ("Central African Republic", "Central African Republic"),
    ("Canada", "Canada"),
    ("Cameroon", "Cameroon"),
    ("Cambodia", "Cambodia"),
    ("Cabo Verde", "Cabo Verde"),
    ("Côte d'Ivoire", "Côte d'Ivoire"),
    ("Burundi", "Burundi"),
    ("Burkina Faso", "Burkina Faso"),
    ("Bulgaria", "Bulgaria"),
    ("Brunei", "Brunei"),
    ("Brazil", "Brazil"),
    ("Botswana", "Botswana"),
    ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
    ("Bolivia", "Bolivia"),
    ("Bhutan", "Bhutan"),
    ("Benin", "Benin"),
    ("Belize", "Belize"),
    ("Belgium", "Belgium"),
    ("Belarus", "Belarus"),
    ("Barbados", "Barbados"),
    ("Bangladesh", "Bangladesh"),
    ("Bahrain", "Bahrain"),
    ("Bahamas", "Bahamas"),
    ("Azerbaijan", "Azerbaijan"),
    ("Austria", "Austria"),
    ("Australia", "Australia"),
    ("Armenia", "Armenia"),
    ("Argentina", "Argentina"),
    ("Antigua and Barbuda", "Antigua and Barbuda"),
    ("Angola", "Angola"),
    ("Andorra", "Andorra"),
    ("Algeria", "Algeria"),
    ("Albania", "Albania"),
    ("Afghanistan", "Afghanistan"),
    ("Zambia", "Zambia"),
    ("Zimbabwe", "Zimbabwe"),
)


MOROCCAN_CITIES = (
    ("city", "city"),
    ("Casablanca", "Casablanca"),
    ("El Kelaa des Srarhna", "El Kelaa des Srarhna"),
    ("Fès", "Fès"),
    ("Tangier", "Tangier"),
    ("Marrakech", "Marrakech"),
    ("Sale", "Sale"),
    ("Mediouna", "Mediouna"),
    ("Rabat", "Rabat"),
    ("Meknès", "Meknès"),
    ("Oujda-Angad", "Oujda-Angad"),
    ("Kenitra", "Kenitra"),
    ("Agadir", "Agadir"),
    ("Tétouan", "Tétouan"),
    ("Taourirt", "Taourirt"),
    ("Temara", "Temara"),
    ("Safi", "Safi"),
    ("Khénifra", "Khénifra"),
    ("Laâyoune", "Laâyoune"),
    ("Mohammedia", "Mohammedia"),
    ("Kouribga", "Kouribga"),
    ("El Jadid", "El Jadid"),
    ("Béni Mellal", "Béni Mellal"),
    ("Ait Melloul", "Ait Melloul"),
    ("Nador", "Nador"),
    ("Taza", "Taza"),
    ("Settat", "Settat"),
    ("Barrechid", "Barrechid"),
    ("Al Khmissat", "Al Khmissat"),
    ("Inezgane", "Inezgane"),
    ("Ksar El Kebir", "Ksar El Kebir"),
    ("Larache", "Larache"),
    ("Guelmim", "Guelmim"),
    ("Berkane", "Berkane"),
    ("Khemis Sahel", "Khemis Sahel"),
    ("Ad Dakhla", "Ad Dakhla"),
    ("Bouskoura", "Bouskoura"),
    ("Al Fqih Ben Salah", "Al Fqih Ben Salah"),
    ("Oued Zem", "Oued Zem"),
    ("Sidi Slimane", "Sidi Slimane"),
    ("Errachidia", "Errachidia"),
    ("Guercif", "Guercif"),
    ("Oulad Teïma", "Oulad Teïma"),
    ("Ben Guerir", "Ben Guerir"),
    ("Sefrou", "Sefrou"),
    ("Fnidq", "Fnidq"),
    ("Sidi Qacem", "Sidi Qacem"),
    ("Moulay Abdallah", "Moulay Abdallah"),
    ("Youssoufia", "Youssoufia"),
    ("Martil", "Martil"),
    ("Aïn Harrouda", "Aïn Harrouda"),
    ("Skhirate", "Skhirate"),
    ("Ouezzane", "Ouezzane"),
    ("Sidi Yahya Zaer", "Sidi Yahya Zaer"),
    ("Al Hoceïma", "Al Hoceïma"),
    ("M’diq", "M’diq"),
    ("Sidi Bennour", "Sidi Bennour"),
    ("Midalt", "Midalt"),
    ("Azrou", "Azrou"),
    ("My Drarga", "My Drarga"),
    ("Ain El Aouda", "Ain El Aouda"),
    ("Beni Yakhlef", "Beni Yakhlef"),
    ("Ad Darwa", "Ad Darwa"),
    ("Al Aaroui", "Al Aaroui"),
    ("Qasbat Tadla", "Qasbat Tadla"),
    ("Boujad", "Boujad"),
    ("Jerada", "Jerada"),
    ("Mrirt", "Mrirt"),
    ("El Aïoun", "El Aïoun"),
    ("Azemmour", "Azemmour"),
    ("Temsia", "Temsia"),
    ("Zagora", "Zagora"),
    ("Ait Ourir", "Ait Ourir"),
    ("Aziylal", "Aziylal"),
    ("Sidi Yahia El Gharb", "Sidi Yahia El Gharb"),
    ("Biougra", "Biougra"),
    ("Zaïo", "Zaïo"),
    ("Aguelmous", "Aguelmous"),
    ("El Hajeb", "El Hajeb"),
    ("Zeghanghane", "Zeghanghane"),
    ("Imzouren", "Imzouren"),
    ("Tit Mellil", "Tit Mellil"),
    ("Mechraa Bel Ksiri", "Mechraa Bel Ksiri"),
    ("Al ’Attawia", "Al ’Attawia"),
    ("Demnat", "Demnat"),
    ("Arfoud", "Arfoud"),
    ("Tameslouht", "Tameslouht"),
    ("Bou Arfa", "Bou Arfa"),
    ("Sidi Smai’il", "Sidi Smai’il"),
    ("Souk et Tnine Jorf el Mellah", "Souk et Tnine Jorf el Mellah"),
    ("Mehdya", "Mehdya"),
    ("Aïn Taoujdat", "Aïn Taoujdat"),
    ("Chichaoua", "Chichaoua"),
    ("Tahla", "Tahla"),
    ("Oulad Yaïch", "Oulad Yaïch"),
    ("Moulay Bousselham", "Moulay Bousselham"),
    ("Iheddadene", "Iheddadene"),
    ("Missour", "Missour"),
    ("Zawyat ech Cheïkh", "Zawyat ech Cheïkh"),
    ("Bouknadel", "Bouknadel"),
    ("Oulad Tayeb", "Oulad Tayeb"),
    ("Oulad Barhil", "Oulad Barhil"),
    ("Bir Jdid", "Bir Jdid"),
    ("Tifariti", "Tifariti"),
    ("other", _("Autre")),
)
